// Assembly Hidistro.UI.Common.Controls, Version 2.1.5557.31513

[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Web.UI.WebResource("Hidistro.UI.Common.Controls.ImageUploader.script.upload.js", "text/javascript")]
[assembly: System.Reflection.AssemblyCompany("QDX Dev Team")]

[assembly: System.Reflection.AssemblyInformationalVersion("2.1")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Web.UI.WebResource("Hidistro.UI.Common.Controls.ImageUploader.images.upload.png", "image/png")]
[assembly: System.Reflection.AssemblyProduct("Hishop")]
[assembly: System.Web.UI.WebResource("Hidistro.UI.Common.Controls.ImageUploader.css.style.css", "text/css")]
[assembly: System.Reflection.AssemblyTitle("UI.Common.Controls")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.InteropServices.Guid("fa868943-3fd1-475f-9966-995403994b49")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDescription("Debug")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2015 - 2016 QDX. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Web.UI.WebResource("Hidistro.UI.Common.Controls.region.helper.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("Hidistro.UI.Common.Controls.ImageUploader.script.upimg.js", "text/javascript")]
